version: "3.2"

services:

  sped-efd:
    image: ralexsander/sped:efd
    container_name: sped-efd
    volumes:
      - ./recursos:/home/sped/ProgramasSPED/Fiscal2/recursos
      - ./arquivos:/home/sped/arquivos
    environment:
      - DISPLAY=host.docker.internal:0
    restart: "no"